AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  partition-manager

  Sample SAM Template for partition-manager

Parameters:
  Application:
    Type: String
  SubApplication:
    Type: String
  Environment:
    Type: String
  QueryOutputLocation:
    Type: String
  Database:
    Type: String
  TableName:
    Type: String
  LookbackHours:
    Type: Number
    Description: "Number of hours to lookback when constructing add partition call"
    Default: 6
  Region:
    Type: String
    Default: 'us-east-1'
  LogLevel:
    Type: String
    Default: INFO
  

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  PartitionManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: partition_manager/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          DATABASE_NAME: !Ref Database
          TABLE_NAME: !Ref TableName
          LOOKBACK_HOURS: !Ref LookbackHours
          REGION: !Ref Region
          OUTPUT_LOCATION: !Ref QueryOutputLocation
      Events:
        RunPartitionFetcher:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Policies:
        - AthenaQueryPolicy:
            WorkGroupName: primary
        - Statement:
          - Sid: GluePermissions
            Effect: Allow
            Action:
            - glue:*
            Resource: '*'
          - Sid: S3PutQueryResultsPermissions
            Effect: Allow
            Action:
            - s3:GetBucketLocation
            - s3:GetObject
            - s3:ListBucket
            - s3:ListBucketMultipartUploads
            - s3:ListMultipartUploadParts
            - s3:AbortMultipartUpload
            - s3:PutObject
            Resource:
              - !Sub
                - "arn:aws:s3:::${bucket}/*"
                - { bucket: !Ref QueryOutputLocation }
              - !Sub
                - "arn:aws:s3:::${bucket}"
                - { bucket: !Ref QueryOutputLocation }

Outputs:
  PartitionaManagerFunction:
    Description: "Partition Manager Lambda Function ARN"
    Value: !GetAtt PartitionManagerFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PartitionManagerFunctionRole.Arn
